### ISSUE TITLE
[JOSS review]:  Xponge package has no automated tests

### ISSUE THREAD

**Issue by ojeda-e** [Xia-Yijie/Xponge#1]
As part of the JOSS review, the Xponge package should include automated tests. 

Description
----------------
Currently, the Xponge repo has a [tests_standard/](https://github.com/Xia-Yijie/Xponge/tree/master/test_standard) folder that includes files with the `test_` prefix. These files are, however, text files instead of `.py` files with unit tests. 
With no automated tests, the functionality of the code cannot be assessed. 

Suggested approach
----------------------------
To fix this issue, please add automated test to verify functionality of your code. Please check the documentation of the [Pytest](https://docs.pytest.org/en/7.1.x/) suite. Alternatively you can check [Unittest](https://docs.python.org/3/library/unittest.html) framework. 

Documentation should include instructions to run Xponge tests locally.

**Comment by Xia-Yijie** [comment]
I added an automated test by using `Xponge test`, but it was not implemented by the framework of Pytest or Unittest. Now I have re-implemented three tests by the framework Unittest, and I will write the instructions to the documentation.

**Comment by Xia-Yijie** [comment]
I added an automated test by using `Xponge test`, but it was not implemented by the framework of Pytest or Unittest. Now I have re-implemented three tests by the framework Unittest, and I will write the instructions to the documentation.

**Comment by ojeda-e** [comment]
Thanks, @Xia-Yijie . Just to keep in mind, it is highly recommended to have tests that verify all functionality of your code since it allows you to identify possible flaws in the code base. Additionally, it may be handy in the future if refactoring is needed.
