### ISSUE TITLE
Add contributor guidelines

### ISSUE THREAD

**Issue by hmacdope** [Xia-Yijie/Xponge#13]
Please add something to indicate how to contribute to XPONGE and get involved as per the JOSS guidelines. 
See this as an example. https://userguide.mdanalysis.org/stable/contributing.html

**Comment by Xia-Yijie** [comment]
Thanks for your suggestion, and I will add one reStructuredText file to indicate how to contribute today

**Comment by ojeda-e** [comment]
@hmacdope I saw the section for contribution added to README and docs. Is it enough to close this issue?

**Comment by hmacdope** [comment]
@ojeda-e enough to close in my opinion :)

**Comment by Xia-Yijie** [comment]
As the issue proposer think it is enough to close, I am going to close the issue. If you think there is still something that need to do later, feel free to re-open the issue.
