### ISSUE TITLE
[JOSS review]: support across different OS

### ISSUE THREAD

**Issue by ojeda-e** [Xia-Yijie/Xponge#4]
Description
-----------------
The README does not provide information about the supported platform. Given the lack of CI in the package is hard to judge the functionality on different Operating Systems (OS). 

Question
-----------------
@Xia-Yijie, is the functionality of Xponge available in all SO (Linux/Mac/Windows)? 

 This information should be provided to the user and should be clearly stated in the documentation 
 
 To fix this issue:
 
- [x] Add supported OS to docs pages #3

**Comment by Xia-Yijie** [comment]
Yes, Xponge is available in all OS, but some functions to do the quantum chemistry calculations can not be used on Windows because `pyscf` is not available on Windows. I will write the information to the README.md and the detailed documentation.

**Comment by ojeda-e** [comment]
@Xia-Yijie please ping me once you add this info to your README and docs to close this issue.

**Comment by Xia-Yijie** [comment]
@ojeda-e I have added the information to the [README](https://github.com/Xia-Yijie/Xponge/blob/master/README.md#installation) (the first paragraph of installation) and [docs](https://spongemm.cn/xponge_doc/index.html) (the section `How can I get Xponge` in the index page).

**Comment by ojeda-e** [comment]
Thanks @Xia-Yijie, is it possible to specify what is not available on Windows? A note in the docs will be sufficient. It's better to be clear with the user about the limitations when working on Windows. Once that is cleared out I'll close this issue.

**Comment by Xia-Yijie** [comment]
@ojeda-e now a link to [the detailed list](https://spongemm.cn/xponge_doc/dependency.html#unavalable-functions-on-windows) has been added to [the first paragraph of installation in README](https://github.com/Xia-Yijie/Xponge/blob/master/README.md#installation) and the hints have been added to the API documentation of the related functions, too.

**Comment by ojeda-e** [comment]
Thanks @Xia-Yijie
I'm closing this issue
