### ISSUE TITLE
[JOSS review]: Is the list of authors incomplete?

### ISSUE THREAD

**Issue by ojeda-e** [Xia-Yijie/Xponge#5]
Description
----------------
The user with the GitHub handle @SummerJustNice seems to have made significant contributions to the Xponge package. (See [contributions link](https://github.com/Xia-Yijie/Xponge/graphs/contributors)).  

Question
-------------
@Xia-Yijie , could you please provide a brief explanation on why @SummerJustNice is not included in list of authors? Is the list of authors incomplete?

Other suggestions:
--------------------------
If the list of authors is incomplete, please update your manuscript accordingly.

**Comment by Xia-Yijie** [comment]
@SummerJustNice is one of my accounts. I was not familiar with the usage of `git` when I started to write the code, so I did not use the same E-mail when I committed. Is there a method to correct this?

**Comment by SummerJustNice** [comment]
I am one of [Xia-Yijie](https://github.com/Xia-Yijie)'s accounts

**Comment by ojeda-e** [comment]
Thanks for clarifying. Would you please add your information to the accounts to identify that both user names are the same contributor?
Once that is done we can close this issue.

**Comment by Xia-Yijie** [comment]
I have added a line "Alternative account @Xia-Yijie" to @SummerJustNice's bio, and added a line "Alternative account @SummerJustNice " to the bio of this account. Is there anything else that I need to do?

**Comment by ojeda-e** [comment]
That's enough. Thanks.
