### ISSUE TITLE
[JOSS review] Base directory cluttered with forcefield files that are not organised 

### ISSUE THREAD

**Issue by hmacdope** [Xia-Yijie/Xponge#7]
The base directory is cluttered with unorganised forcefield files and also has some junk?

- [x]  organise the FF files into some kind of folder and provide license terms for each and citations. 
- [x] Remove or clarify role of  the apparent junk PDB files [0.15_80_10_pH6.5_6lzg.result.pdb](https://github.com/Xia-Yijie/Xponge/blob/master/0.15_80_10_pH6.5_6lzg.result.pdb) etc.

**Comment by Xia-Yijie** [comment]
I have organised the FF files and only keep them in the fold `Xponge/forcefield` now. I cite them in my `.py` file, and it can be seen after importing the module. For example, after importing `Xponge.forcefield.amber.ff14sb`, the citation for ff14SB can be seen. I can not find the license for the forcefields. I think the original authors may not have provided the license.

**Comment by Xia-Yijie** [comment]
I have organised the FF files and only keep them in the fold `Xponge/forcefield` now. I cite them in my `.py` file, and it can be seen after importing the module. For example, after importing `Xponge.forcefield.amber.ff14sb`, the citation for ff14SB can be seen. I can not find the license for the forcefields. I think the original authors may not have provided the license.
